### ISSUE TITLE
Inverted HTTP verbs

### ISSUE THREAD

**Issue by wolfracer** [p8ul/django-rest-framework-boilerplate#9]
i think the convention is that you use POST for creating, and GET for retriving and listing users

**Comment by p8ul** [comment]
Hi @wolfracer , 

Do you mind include a piece of code or link to the code that you believe has broken the HTTP convention?  I would also advise you to go through the [DRF generic views API](https://www.django-rest-framework.org/api-guide/generic-views/). For instance, to retrieve & list users, `class UserListAPIView(ListAPIView):` We are using [ListAPIView](https://www.django-rest-framework.org/api-guide/generic-views/#listapiview) which provides GET method handler.

**Comment by wolfracer** [comment]
> Hi @wolfracer ,
> 
> Do you mind include a piece of code or link to the code that you believe has broken the HTTP convention? I would also advise you to go through the [DRF generic views API](https://www.django-rest-framework.org/api-guide/generic-views/). For instance, to retrieve & list users, `class UserListAPIView(ListAPIView):` We are using [ListAPIView](https://www.django-rest-framework.org/api-guide/generic-views/#listapiview) which provides GET method handler.

i think the problem its just in the readme file, it says GET for create user and POST for listing users

**Comment by wolfracer** [comment]
@p8ul

**Comment by p8ul** [comment]
Sure @wolfracer , sorry about the README file misinformation. I have updated it to show the correct HTTP verb. Feel free to raise a PR to improve the boilerplate :)
